repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: no-commit-to-branch
      - id: end-of-file-fixer
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        args: ["-l 100", "--check"]
  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.770
      hooks:
        -   id: mypy
